# Generated by Django 3.2.7 on 2021-09-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='title',
        ),
    ]
