# Generated by Django 3.2.7 on 2021-09-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoS', '0002_rename_description_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(default=None, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.CharField(max_length=256, unique=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=126, verbose_name='Title'),
        ),
    ]
